# Generated by Django 3.2 on 2021-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('bt', models.IntegerField()),
                ('co', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('year', models.IntegerField()),
                ('subname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'questionBank',
            },
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
