# Generated by Django 3.1.3 on 2025-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210925_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='co',
            new_name='subject_code',
        ),
    ]
