# Generated by Django 3.1.3 on 2025-05-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20250427_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='bt',
        ),
    ]
